---
- name: '[EL] Install cvmfs repository'
  yum:
    name: 'https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm'
    state: present

- name: '[EL] Install cvmfs client'
  yum:
    name: '{{ item }}'
    update_cache: yes
    state: present
  with_items:
   - cvmfs
   - cvmfs-config-default
