---
- name: '[EL] add cvmfs user with uid 1000'
  user:
    name: cvmfs
    comment: cvmfs user
    uid: 1000
    group: cvmfs
    home: /var/lib/cvmfs
  when: snapshotter|boolean
  
- name: '[EL] Install cvmfs repository'
  yum:
    name: 'https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm'
    state: present
  register: install_yum_repo
  ignore_errors: yes

- name: '[EL] Install cvmfs client'
  yum:
    name: '{{ item }}'
    update_cache: yes
    state: present
  with_items:
   - cvmfs
   - cvmfs-config-default
  register: install_cvmfs
  ignore_errors: yes
  when: install_yum_repo.failed is undefined

- name: '[EL] Copy rpm'
  copy:
    src: '{{ item }}'
    dest: '/tmp/'
  with_items:
    - 'cvmfs-2.10.1-1.el9.x86_64.rpm'
    - 'cvmfs-config-default-2.0-2.noarch.rpm'
  when: install_yum_repo.failed is defined or install_cvmfs.failed is defined

- name: '[EL] Install cvmfs from rpm'
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - '/tmp/cvmfs-2.10.1-1.el9.x86_64.rpm'
    - '/tmp/cvmfs-config-default-2.0-2.noarch.rpm'
  when: install_yum_repo.failed is defined or install_cvmfs.failed is defined
