---
- name: change user id 1000 to 1234
  command:
   cmd: ["(getent group 1000 > /dev/null) && (sed -i "s|1000|1234|g" /etc/group)",\
        "(getent passwd 1000 > /dev/null) && (sed -i "s|1000|1234|g" /etc/passwd)",\
        "chown -R 1234.1234 `getent passwd 1234 | cut -d: -f6`"]
  ignore_errors: yes
  
- include: client_install_centos.yml
  when: ansible_os_family == "RedHat"

- include: client_install_ubuntu.yml
  when: ansible_os_family == "Debian"
