---
- name: Get uid 1000 user info
  getent:
    database: passwd
    key: 1000
  ignore_errors: yes
  register: user1000
  
- name: Create the cvmfs user with UID 1000 if it doesn't exist
  user:
    name: cvmfs
    uid: 1000
    group: users
    state: present
  when: user1000.rc != 0
    
- include: client_install_centos.yml
  when: ansible_os_family == "RedHat"

- include: client_install_ubuntu.yml
  when: ansible_os_family == "Debian"
