---
- name: '[Ubuntu] Add cvmfs user with uid 1000'
  user:
    name: cvmfs
    comment: cvmfs user
    uid: 1000
    group: cvmfs
    system: true
    home: /cvmfs
  when: snapshotter|bool

- name: '[Ubuntu] Install cmvfs client repository'
  apt:
    deb: https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb

- name: '[Ubuntu] Install cvmfs client'
  apt:
    name: '{{ item }}'
    update_cache: yes
  with_items:
   - cvmfs
   - cvmfs-config-default
