---
# tasks file for cvmfs-client

- name: Skip installation of cvmfs if /cvmfs path exists
  stat:
    path: /cvmfs
  register: p
  
- include: client_install.yml
  when: not p.stat.isdir

- command: 'cvmfs_config stat -v {{ repository_name}}'
  register: cvmfs_stat
  ignore_errors: yes

- include: client_config.yml
  when: cvmfs_stat.rc != 0

- include: snapshotter_install.yml
  when: snapshotter|bool

- include: snapshotter_config.yml
  when: snapshotter|bool
