---
# tasks file for cvmfs-client

- name: Skip installation of cvmfs if /cvmfs path exists
  stat:
    path: /cvmfs
  register: p
  
- include_tasks: client_install.yml
  name: Installing client
  when: 
    - p.stat.isdir is not defined
    - repository_name != ""

- command: 'cvmfs_config stat -v {{ repository_name}}'
  register: cvmfs_stat
  ignore_errors: yes
  when: repository_name != ""

- include_tasks: client_config.yml
  name: Configuring client
  when:
    - cvmfs_stat.rc != 0
    - repository_name != ""

- include_tasks: snapshotter_install.yml
  name: Installing snapshotter
  when: 
    - snapshotter|bool
    - repository_name != ""

- include_tasks: snapshotter_config.yml
  name: Configuring snapshotter
  when: 
    - snapshotter|bool
    - repository_name != ""
