---
# tasks file for cvmfs-client

- include: client_install.yml

- command: 'cvmfs_config stat -v'
  register: cvmfs_stat
  ignore_errors: yes

- include: client_config.yml
  when: cvmfs_stat.rc != 0

- include: snapshotter_install.yml
  when: snapshotter|bool

- include: snapshotter_config.yml
  when: snapshotter|bool
