---
# tasks file for cvmfs-client

- name: change user id 1000 to 1234
  command:
    cmd: ["(getent group 1000 > /dev/null) && (sed -i "s|1000|1234|g" /etc/group)",\
          "(getent passwd 1000 > /dev/null) && (sed -i "s|1000|1234|g" /etc/passwd)",\
          "chown -R 1234.1234 `getent passwd 1234 | cut -d: -f6`"]
  ignore_errors: yes
  when: snapshotter|bool

- include: client_install.yml

- command: 'cvmfs_config stat -v {{repository_name}}'
  register: cvmfs_stat
  ignore_errors: yes

- include: client_config.yml
  when: cvmfs_stat.rc != 0

- include: snapshotter_install.yml
  when: snapshotter|bool

- include: snapshotter_config.yml
  when: snapshotter|bool
