- name: Install go and other packages with yum
  yum:
    name: ['go', 'cvmfs', 'cvmfs-config-default']
    update_cache: yes
    state: present
    
- name: Creates directories for git clone
  file: path={{ item.path}} state=directory
  with_items:
    - { path: "{{snapshotter_path}}/cvmfs" }
    - { path: "{{snapshotter_path}}/nerdctl" }
    
- name: Clone git repositories
  git: repo={{ item.repo }} dest={{ item.dest }} clone=yes version={{item.version}}
  with_items:
    - { repo: "https://github.com/marcoverl/cvmfs", dest: "{{snapshotter_path}}/cvmfs", version: "fix-snapshotter", depth: 1 }
  
- name: Build snapshotter 
  command: make chdir={{snapshotter_path}}/cvmfs/snapshotter
  environment: 
    PREFIX: "/usr/local/bin/"

- name: Download nerdctl archive
  get_url:
    url: "https://github.com/marcoverl/nerdctl/releases/download/untagged-89bd856581f38bd91638/nerdctl-1.6.3-linux-amd64.tar.gz"
    dest: "/tmp/nerdctl-1.6.3-linux-amd64.tar.gz"
    register: download_result
    
- name: Extract nerdctl archive
    command: "tar -C /usr/local/bin -zxvf /tmp/nerdctl-1.6.3-linux-amd64.tar.gz"
    when: download_result.changed
