- name: Creates directory
  file:
    path: /etc/containerd-cvmfs-grpc
    state: directory

- name: Copy config files
  copy:
    src: '{{containerd_remote_snapshotter_path}}/script/config/etc/containerd-cvmfs-grpc/config.toml'
    dest: '/etc/containerd-cvmfs-grpc/config.toml'
  when: not cvmfs_preconfigured|bool

- name: Copy config files
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
  - { src: '{{containerd_remote_snapshotter_path}}/script/config/etc/containerd-cvmfs-grpc/config.toml', dest: '/etc/containerd-cvmfs-grpc/config.toml' }
  - { src: '{{containerd_remote_snapshotter_path}}/script/config/etc/systemd/system/cvmfs-snapshotter.service', dest: '/etc/systemd/system/cvmfs-snapshotter.service' }
