- name: Install go with snap
  snap: name=go classic=yes
    
- name: Install other packages
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - make
    - fuse3
    
- name: Creates directories for git clone
  file: path={{ item.path}} state=directory
  with_items:
    - { path: "{{snapshotter_path}}/containerd-remote-snapshotter" }
    - { path: "{{snapshotter_path}}/nerdctl" }
    
- name: Clone git repositories
  git: repo={{ item.repo }} dest={{ item.dest }} clone=yes version={{item.version}}
  with_items:
    - { repo: "https://github.com/marcoverl/containerd-remote-snapshotter", dest: "{{snapshotter_path}}/containerd-remote-snapshotter", version: "HEAD" }
    - { repo: "https://github.com/containerd/nerdctl", dest: "{{snapshotter_path}}/nerdctl", version: "v1.4.0" }
  
- name: Build snapshotter
  command: go mod tidy chdir={{snapshotter_path}}/containerd-remote-snapshotter 
- command: make chdir={{snapshotter_path}}/containerd-remote-snapshotter
  environment: 
    PREFIX: "/usr/local/bin/"
    
- name: Build nerdctl
  command: make chdir={{snapshotter_path}}/nerdctl
- command: make install chdir={{snapshotter_path}}/nerdctl
