- name: Install go with snap
  snap: name=go classic=yes
    
- name: Install other packages
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - make
    - fuse3
    
- name: Clone git repository
  git: repo={{ item.repo }} dest={{ item.dest }} clone=yes version={{item.version}}
  with_items:
    - { repo: "https://github.com/marcoverl/containerd-remote-snapshotter", dest: "{{snapshotter_path}}/containerd-remote-snapshotter", version: "HEAD" }
  
- name: Build snapshotter
  command: go mod tidy chdir={{snapshotter_path}}/containerd-remote-snapshotter 
- command: make chdir={{snapshotter_path}}/containerd-remote-snapshotter
  environment: 
    PREFIX: "/usr/local/bin"
