- name: Creates directory
  file:
    path: /etc/containerd-cvmfs-grpc
    state: directory
  when: not cvmfs_preconfigured|bool
  
- name: Copy config files
  copy:
    src: '{{snapshotter_path}}/containerd-remote-snapshotter/script/config/etc/containerd-cvmfs-grpc/config.toml'
    dest: '/etc/containerd-cvmfs-grpc/config.toml'
  when: not cvmfs_preconfigured|bool

- name: Copy config files
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
  - { src: '{{snapshotter_path}}/containerd-remote-snapshotter/script/config/etc/containerd-cvmfs-grpc/config.toml', dest: '/etc/containerd-cvmfs-grpc/config.toml' }
  - { src: '{{snapshotter_path}}/containerd-remote-snapshotter/script/config/etc/systemd/system/cvmfs-snapshotter.service', dest: '/etc/systemd/system/cvmfs-snapshotter.service' }
  when: not cvmfs_preconfigured|bool
  
- name: replace line
  lineinfile: 
  path: /etc/containerd/config.toml 
  regexp: '{{item.from}}' 
  line: '{{item.to}}'
  backrefs: yes
  with_items:
  - { from: '^(.*)disable_snapshot_annotations(.*)$', to: 'disable_snapshot_annotations = false' }
  - { from: '^(.*)snapshotter(.*)$', to: 'snapshotter = "cvmfs-snapshotter"' }
  when: not cvmfs_preconfigured|bool
