- name: Install go with snap
  snap: name=go classic=yes
  when: ansible_os_family == "Debian
  
- name: Install other packages
  apt:
    name: ['make', 'fuse3']
    state: latest 
    update_cache: yes 
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Install go and other packages with yum
  yum:
    name: ['go', 'cvmfs', 'cvmfs-config-default']
    update_cache: yes
    state: present
  when: ansible_os_family == "RedHat"   
    
- name: Creates directories for git clone
  file: path={{ item.path}} state=directory
  with_items:
    - { path: "{{snapshotter_path}}/cvmfs" }
    - { path: "{{snapshotter_path}}/nerdctl" }
    
- name: Clone git repositories
  git: repo={{ item.repo }} dest={{ item.dest }} clone=yes version={{item.version}}
  with_items:
    - { repo: "https://github.com/marcoverl/cvmfs", dest: "{{snapshotter_path}}/cvmfs", version: "fix-snapshotter", depth: 1 }
    - { repo: "https://github.com/marcoverl/nerdctl", dest: "{{snapshotter_path}}/nerdctl", version: "v1.6.3" }
  
- name: Build snapshotter 
  command: make chdir={{snapshotter_path}}/cvmfs/snapshotter
  environment: 
    PREFIX: "/usr/local/bin/"
    
- name: Build nerdctl
  command: make chdir={{snapshotter_path}}/nerdctl
- command: make install chdir={{snapshotter_path}}/nerdctl
